{% set name = "de-forcefields" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jthorton/de-forcefields/archive/refs/tags/{{ version }}.tar.gz
  sha256: b5e7bb748cf74fee0696864031a9c3a9a9a83710d905f9ba87d0ed86b66f01c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.10
    - pip
  run:
    - python >=3.7,<3.10
    - setuptools
    - openff-toolkit >=0.10.6, <0.11.0
    - smirnoff-plugins >=0.0.3

test:
  imports:
    - deforcefields

about:
  home: https://github.com/jthorton/de-forcefields
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transferable Double Exponential non-bonded potential for condensed phase simulations of small molecules.
  doc_url: https://github.com/jthorton/de-forcefields
  dev_url: https://github.com/qubekit/QUBEKit
  description: |
    OFFXML SMIRNOFF style force field files for use with the OpenFF-Toolkit.

extra:
  recipe-maintainers:
    - jthorton
    - djcole56
    - pavankum
    - SimonBoothroyd
